AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Chatroom
Parameters:
  FunctionNamePrefix:
    Type: String
Resources:
  clientRecords:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: ${FunctionNamePrefix}Client-Records
      PrimaryKey:
        Name: ID
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  Connect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${FunctionNamePrefix}Connect
      Runtime: nodejs10.x
      Handler: index.handler
      CodeUri: s3://r2d2lambdas.app/ec9b3c09d9098d11968d444d5ea11e2a
      Policies:
      - Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource:
            Fn::GetAtt:
            - clientRecords
            - Arn
      Environment:
        Variables:
          TABLE_CR:
            Ref: clientRecords
  Disconnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${FunctionNamePrefix}Disconnect
      Runtime: nodejs10.x
      Handler: index.handler
      CodeUri: s3://r2d2lambdas.app/c98b50d53cce00c5016186eaf9b2924e
      Policies:
      - Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - dynamodb:DeleteItem
          Resource:
            Fn::GetAtt:
            - clientRecords
            - Arn
      Environment:
        Variables:
          TABLE_CR:
            Ref: clientRecords
  Dispatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${FunctionNamePrefix}SendMessage
      Runtime: nodejs10.x
      Handler: index.handler
      CodeUri: s3://r2d2lambdas.app/482ca7265fdf2245821690605b999271
      Policies:
      - Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - dynamodb:UpdateItem
          Resource:
            Fn::GetAtt:
            - clientRecords
            - Arn
      Environment:
        Variables:
          TABLE_CR:
            Ref: clientRecords
